### PR TITLE
fix: Remove unnecessary internet permission

### LINKED ISSUE #3: Permission question
I'm just wondering what the Internet permission is required for. Does the app reach out to some server to convert the URLs?

And while I am here:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

This can easily be avoided by a little change to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

PS: Would be nice if you could include an icon with your Fastlane structures (else your app will show up without one at F-Droid), and if possible also some screenshots :wink:

Thanks in advance!

PS: Your app will [become available here](https://apt.izzysoft.de/packages/sh.unlimi.x2vx) at the IzzyOnDroid repo with the next sync around 6 pm UTC. I've created an icon for it by cutting it out of your featureGraphic, so this is what it will look like then:

image

### PR DESCRIPTION
**Pull request by siketyan**
Closes #3 

I've tested on an emulator and it works perfectly without this permission so removing it.

### CODE REVIEW

**Comment by siketyan** [comment]
@unlimish You will need to use `pull_request_target` trigger instead of `pull_request` to get write permission for **forked** PRs for security reasons. By changing it, GitHub Actions will use the workflow from default branch; changes to the workflow from pull requests will not apply to the run.

**Comment by unlimish** [comment]
~~ah, I replaced key to classic one...~~
I added pull_requests permissions

**Comment by unlimish** [comment]
image
🤔

**Comment by siketyan** [comment]
@unlimish Yes, as I telled you on Discord, the write permissions are not available on forked PRs. Thank you for reviewing this anyway!

**Pull request merged**
